### ISSUE TITLE
Should this library work?

### ISSUE THREAD

**Issue by stvn** [MaxMaes/WebRTCTest#1]
I'm looking to use your lib.  Did you ever have it working?  Thanks in advance!

**Comment by PonyHugger** [comment]
It's not working for me aswell. (cpp_params_create_frame_info bad output format)

**Comment by MaxMaes** [comment]
The version of Kurento that was used did not support trickling ICE yet, but the latest version does. Since the company I work at didn't pursue the Kurento path I haven't updated this with the new Kurento to get it to work.
